### ISSUE TITLE
Wallet-service crashes. 

### ISSUE THREAD

**Issue by sinaizd** [BeamMW/wallet-service#5]
**Bug description**
In this case, there are two points:

- Wallet-service crashes when several dozen login requests are received from the web-wallet.

-  After processing these several dozen requests and logging in, the web-wallet and browser freeze.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open web-wallet.
2. On login screen enter password.
3. Click "open your wallet" several dozen times..

 **Current behaviour:**

**Problem 1.** Wallet-service crashes when several dozen login requests are received from the web-wallet.
**Problem 2.** After logging in, the web-wallet and browser freeze.

**Expected behaviour:**

After the first click, you are logged in, and all others are blocked.

**Browser:**

- Google Chrome
- Version: 83.0.4103.116

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/45556620/87674917-58094d00-c77f-11ea-8efa-4381a081ea26.png)

**Comment by chapati** [comment]
**Problem 1** fixed. Fix is not final, but good enough to release testnet. TODO: keeper crash when _opening flag is ignored. Should not happen in real life but anyway lifetime of keykeeper is not managed correctly. This is for the next version or mainnet release.

**Problem 2** should be fixed in web code. Need to disable 'open wallet' button after the first click

Please test also multiple fast logout then login.

**Comment by sinaizd** [comment]
**Problem 1** fixed and checked.
However, we have other errors:
1. The session doesn't end after logging out of the wallet.
Steps to reproduce the behaviour:
1.Send a lot of login requests
2.Login wallet.
3.Logout wallet.
4.Repeat steps 2,3 several times.
**Current behaviour:**
Error: trying to log in to an already active session
2. Unable to create a wallet.
Error:
{error: {code: -32603, data: "CannotGenerateSecretException", message: "Internal JSON-RPC error."},…}
error: {code: -32603, data: "CannotGenerateSecretException", message: "Internal JSON-RPC error."}
id: 0
jsonrpc: "2.0"
![image](https://user-images.githubusercontent.com/45556620/87939575-f1e33980-caa0-11ea-984c-356e6f2bd300.png)

**Comment by sinaizd** [comment]
Fixed and checked.
> **Problem 1** fixed and checked.
> 1. The session doesn't end after logging out of the wallet.
> 2. Unable to create a wallet.
>
 Now we need to fix problem 2. @iscander01 before fixing problem 2 you need to discuss this with @chapati

**Comment by thanh21698** [comment]
did we have any problem with the  wallet now ? thanks dev
